export const ACTIONS = {
  SET_DRINKS_DATA: "SET DRINKS DATA",
  SET_SEARCH_TEXT: "SET SEARCH TEXT",
  SET_DRINKID: "SET CURRENT DRINK ID",
  OPEN_SIDEBAR: "OPEN SIDEBAR",
  CLOSE_SIDEBAR: "CLOSE SIDEBAR",
  SET_ISLOADING: "SET LOADING FALSE",
  SET_SINGLEDRINK_DATA: "SET SINGLE DRINK DATA",
  SET_SINGLEDRINK_INGREDIENTS: "SET SINGLE DRINK INGREDIENTS",
  SET_SEARCH_RESULT: "SET SEARCH RESULT",
};
